//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_reserva
    {
        public string id_reserva { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> puntos_servicios_redimidos { get; set; }
        public long id_detalle_reserva { get; set; }
    
        public virtual servicios servicios { get; set; }
        public virtual reservas reservas { get; set; }
    }
}
