//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RacePuntosEntities : DbContext
    {
        public RacePuntosEntities()
            : base("name=RacePuntosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<detalle_puntos> detalle_puntos { get; set; }
        public virtual DbSet<detalle_reserva> detalle_reserva { get; set; }
        public virtual DbSet<detalle_vehiculos> detalle_vehiculos { get; set; }
        public virtual DbSet<estaciones_de_servicio> estaciones_de_servicio { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<puntos> puntos { get; set; }
        public virtual DbSet<reservas> reservas { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    }
}
