//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class puntos
    {
        public int id_puntos_actuales { get; set; }
        public string id_usuario_puntos { get; set; }
        public string id_usuario_plataforma { get; set; }
        public Nullable<int> puntos_acumulados { get; set; }
    
        public virtual personas personas { get; set; }
    }
}
