//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RacePuntosEntities : DbContext
    {
        public RacePuntosEntities()
            : base("name=RacePuntosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cargos> cargos { get; set; }
        public virtual DbSet<detalle_puntos> detalle_puntos { get; set; }
        public virtual DbSet<detalle_reserva> detalle_reserva { get; set; }
        public virtual DbSet<detalle_vehiculos> detalle_vehiculos { get; set; }
        public virtual DbSet<estaciones_de_servicio> estaciones_de_servicio { get; set; }
        public virtual DbSet<personas> personas { get; set; }
        public virtual DbSet<puntos> puntos { get; set; }
        public virtual DbSet<reservas> reservas { get; set; }
        public virtual DbSet<servicios> servicios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<vehiculo> vehiculo { get; set; }
    
        public virtual ObjectResult<consulta_disponibilidad_estacion_Result> consulta_disponibilidad_estacion(Nullable<int> id_estacion_recibida, string fecha_recibida, Nullable<int> hora_recibida)
        {
            var id_estacion_recibidaParameter = id_estacion_recibida.HasValue ?
                new ObjectParameter("id_estacion_recibida", id_estacion_recibida) :
                new ObjectParameter("id_estacion_recibida", typeof(int));
    
            var fecha_recibidaParameter = fecha_recibida != null ?
                new ObjectParameter("fecha_recibida", fecha_recibida) :
                new ObjectParameter("fecha_recibida", typeof(string));
    
            var hora_recibidaParameter = hora_recibida.HasValue ?
                new ObjectParameter("hora_recibida", hora_recibida) :
                new ObjectParameter("hora_recibida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<consulta_disponibilidad_estacion_Result>("consulta_disponibilidad_estacion", id_estacion_recibidaParameter, fecha_recibidaParameter, hora_recibidaParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> consulta_puntos_acumulados(string id_usuario_ingreso)
        {
            var id_usuario_ingresoParameter = id_usuario_ingreso != null ?
                new ObjectParameter("id_usuario_ingreso", id_usuario_ingreso) :
                new ObjectParameter("id_usuario_ingreso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("consulta_puntos_acumulados", id_usuario_ingresoParameter);
        }
    
        public virtual int ingreso_detalle_puntos_reserva(Nullable<int> id_estacion_recibido, Nullable<int> id_puntos_servicio_recibido, Nullable<int> id_puntos_actuales_recibido, Nullable<int> puntos_reserva_recibido)
        {
            var id_estacion_recibidoParameter = id_estacion_recibido.HasValue ?
                new ObjectParameter("id_estacion_recibido", id_estacion_recibido) :
                new ObjectParameter("id_estacion_recibido", typeof(int));
    
            var id_puntos_servicio_recibidoParameter = id_puntos_servicio_recibido.HasValue ?
                new ObjectParameter("id_puntos_servicio_recibido", id_puntos_servicio_recibido) :
                new ObjectParameter("id_puntos_servicio_recibido", typeof(int));
    
            var id_puntos_actuales_recibidoParameter = id_puntos_actuales_recibido.HasValue ?
                new ObjectParameter("id_puntos_actuales_recibido", id_puntos_actuales_recibido) :
                new ObjectParameter("id_puntos_actuales_recibido", typeof(int));
    
            var puntos_reserva_recibidoParameter = puntos_reserva_recibido.HasValue ?
                new ObjectParameter("puntos_reserva_recibido", puntos_reserva_recibido) :
                new ObjectParameter("puntos_reserva_recibido", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ingreso_detalle_puntos_reserva", id_estacion_recibidoParameter, id_puntos_servicio_recibidoParameter, id_puntos_actuales_recibidoParameter, puntos_reserva_recibidoParameter);
        }
    
        public virtual int ingreso_detalle_reserva(Nullable<int> id_reserva_recibida, Nullable<int> id_servicio_recibido, Nullable<int> puntos_reserva_redimidos)
        {
            var id_reserva_recibidaParameter = id_reserva_recibida.HasValue ?
                new ObjectParameter("id_reserva_recibida", id_reserva_recibida) :
                new ObjectParameter("id_reserva_recibida", typeof(int));
    
            var id_servicio_recibidoParameter = id_servicio_recibido.HasValue ?
                new ObjectParameter("id_servicio_recibido", id_servicio_recibido) :
                new ObjectParameter("id_servicio_recibido", typeof(int));
    
            var puntos_reserva_redimidosParameter = puntos_reserva_redimidos.HasValue ?
                new ObjectParameter("puntos_reserva_redimidos", puntos_reserva_redimidos) :
                new ObjectParameter("puntos_reserva_redimidos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ingreso_detalle_reserva", id_reserva_recibidaParameter, id_servicio_recibidoParameter, puntos_reserva_redimidosParameter);
        }
    
        public virtual int ingreso_puntos(string id_usuario_recibido, string id_usuario_plataforma_recibido, Nullable<int> puntos_acumulados_recibidos)
        {
            var id_usuario_recibidoParameter = id_usuario_recibido != null ?
                new ObjectParameter("id_usuario_recibido", id_usuario_recibido) :
                new ObjectParameter("id_usuario_recibido", typeof(string));
    
            var id_usuario_plataforma_recibidoParameter = id_usuario_plataforma_recibido != null ?
                new ObjectParameter("id_usuario_plataforma_recibido", id_usuario_plataforma_recibido) :
                new ObjectParameter("id_usuario_plataforma_recibido", typeof(string));
    
            var puntos_acumulados_recibidosParameter = puntos_acumulados_recibidos.HasValue ?
                new ObjectParameter("puntos_acumulados_recibidos", puntos_acumulados_recibidos) :
                new ObjectParameter("puntos_acumulados_recibidos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ingreso_puntos", id_usuario_recibidoParameter, id_usuario_plataforma_recibidoParameter, puntos_acumulados_recibidosParameter);
        }
    
        public virtual int ingreso_reserva(Nullable<int> id_estacion_recibido, string id_usuario_recibido, string fecha_reserva_recibida, Nullable<int> puntos_reserva_recibido, Nullable<int> hora_reserva_recibida)
        {
            var id_estacion_recibidoParameter = id_estacion_recibido.HasValue ?
                new ObjectParameter("id_estacion_recibido", id_estacion_recibido) :
                new ObjectParameter("id_estacion_recibido", typeof(int));
    
            var id_usuario_recibidoParameter = id_usuario_recibido != null ?
                new ObjectParameter("id_usuario_recibido", id_usuario_recibido) :
                new ObjectParameter("id_usuario_recibido", typeof(string));
    
            var fecha_reserva_recibidaParameter = fecha_reserva_recibida != null ?
                new ObjectParameter("fecha_reserva_recibida", fecha_reserva_recibida) :
                new ObjectParameter("fecha_reserva_recibida", typeof(string));
    
            var puntos_reserva_recibidoParameter = puntos_reserva_recibido.HasValue ?
                new ObjectParameter("puntos_reserva_recibido", puntos_reserva_recibido) :
                new ObjectParameter("puntos_reserva_recibido", typeof(int));
    
            var hora_reserva_recibidaParameter = hora_reserva_recibida.HasValue ?
                new ObjectParameter("hora_reserva_recibida", hora_reserva_recibida) :
                new ObjectParameter("hora_reserva_recibida", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ingreso_reserva", id_estacion_recibidoParameter, id_usuario_recibidoParameter, fecha_reserva_recibidaParameter, puntos_reserva_recibidoParameter, hora_reserva_recibidaParameter);
        }
    
        public virtual ObjectResult<logeo_persona_Result> logeo_persona(string documento_ingresado, string contrasena_ingresada)
        {
            var documento_ingresadoParameter = documento_ingresado != null ?
                new ObjectParameter("documento_ingresado", documento_ingresado) :
                new ObjectParameter("documento_ingresado", typeof(string));
    
            var contrasena_ingresadaParameter = contrasena_ingresada != null ?
                new ObjectParameter("contrasena_ingresada", contrasena_ingresada) :
                new ObjectParameter("contrasena_ingresada", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<logeo_persona_Result>("logeo_persona", documento_ingresadoParameter, contrasena_ingresadaParameter);
        }
    
        public virtual ObjectResult<MarcasVehiculo_Result> MarcasVehiculo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MarcasVehiculo_Result>("MarcasVehiculo");
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_id_estacion_servicio(string nombre_estacion)
        {
            var nombre_estacionParameter = nombre_estacion != null ?
                new ObjectParameter("nombre_estacion", nombre_estacion) :
                new ObjectParameter("nombre_estacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_id_estacion_servicio", nombre_estacionParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_id_puntos_actual_max(string id_usuario)
        {
            var id_usuarioParameter = id_usuario != null ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_id_puntos_actual_max", id_usuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_id_puntos_actual_max_para_ingreso_detalle_puntos(string id_usuario_recibido)
        {
            var id_usuario_recibidoParameter = id_usuario_recibido != null ?
                new ObjectParameter("id_usuario_recibido", id_usuario_recibido) :
                new ObjectParameter("id_usuario_recibido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_id_puntos_actual_max_para_ingreso_detalle_puntos", id_usuario_recibidoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_id_puntos_actuales(string id_usuario_ingreso)
        {
            var id_usuario_ingresoParameter = id_usuario_ingreso != null ?
                new ObjectParameter("id_usuario_ingreso", id_usuario_ingreso) :
                new ObjectParameter("id_usuario_ingreso", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_id_puntos_actuales", id_usuario_ingresoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_id_puntos_servicio(string nombre_servicio_recibido)
        {
            var nombre_servicio_recibidoParameter = nombre_servicio_recibido != null ?
                new ObjectParameter("nombre_servicio_recibido", nombre_servicio_recibido) :
                new ObjectParameter("nombre_servicio_recibido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_id_puntos_servicio", nombre_servicio_recibidoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_id_reserva_ultima(string id_usuario_recibido)
        {
            var id_usuario_recibidoParameter = id_usuario_recibido != null ?
                new ObjectParameter("id_usuario_recibido", id_usuario_recibido) :
                new ObjectParameter("id_usuario_recibido", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_id_reserva_ultima", id_usuario_recibidoParameter);
        }
    
        public virtual ObjectResult<obtener_id_servicio_puntos_compra_Result> obtener_id_servicio_puntos_compra(Nullable<int> id_puntos_actuales_ingreso)
        {
            var id_puntos_actuales_ingresoParameter = id_puntos_actuales_ingreso.HasValue ?
                new ObjectParameter("id_puntos_actuales_ingreso", id_puntos_actuales_ingreso) :
                new ObjectParameter("id_puntos_actuales_ingreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<obtener_id_servicio_puntos_compra_Result>("obtener_id_servicio_puntos_compra", id_puntos_actuales_ingresoParameter);
        }
    
        public virtual ObjectResult<string> obtener_nombre_servicio(Nullable<int> id_servicio_ingreso)
        {
            var id_servicio_ingresoParameter = id_servicio_ingreso.HasValue ?
                new ObjectParameter("id_servicio_ingreso", id_servicio_ingreso) :
                new ObjectParameter("id_servicio_ingreso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("obtener_nombre_servicio", id_servicio_ingresoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> obtener_puntos_acumulados_actual(Nullable<int> id_puntos_maximo)
        {
            var id_puntos_maximoParameter = id_puntos_maximo.HasValue ?
                new ObjectParameter("id_puntos_maximo", id_puntos_maximo) :
                new ObjectParameter("id_puntos_maximo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("obtener_puntos_acumulados_actual", id_puntos_maximoParameter);
        }
    
        public virtual int registro_persona(string tipo_documento_ingresado, string documento_ingresado, string contrasena_ingresada, string rol_ingresado, string cargo_ingresado, string id_usuario_creacion, string nombres_ingresados, string apellidos_ingresados, string fecha_nacimiento_ingresado, string direccion_ingresado, string numero_celular_ingresado, string correo_ingresado)
        {
            var tipo_documento_ingresadoParameter = tipo_documento_ingresado != null ?
                new ObjectParameter("tipo_documento_ingresado", tipo_documento_ingresado) :
                new ObjectParameter("tipo_documento_ingresado", typeof(string));
    
            var documento_ingresadoParameter = documento_ingresado != null ?
                new ObjectParameter("documento_ingresado", documento_ingresado) :
                new ObjectParameter("documento_ingresado", typeof(string));
    
            var contrasena_ingresadaParameter = contrasena_ingresada != null ?
                new ObjectParameter("contrasena_ingresada", contrasena_ingresada) :
                new ObjectParameter("contrasena_ingresada", typeof(string));
    
            var rol_ingresadoParameter = rol_ingresado != null ?
                new ObjectParameter("rol_ingresado", rol_ingresado) :
                new ObjectParameter("rol_ingresado", typeof(string));
    
            var cargo_ingresadoParameter = cargo_ingresado != null ?
                new ObjectParameter("cargo_ingresado", cargo_ingresado) :
                new ObjectParameter("cargo_ingresado", typeof(string));
    
            var id_usuario_creacionParameter = id_usuario_creacion != null ?
                new ObjectParameter("id_usuario_creacion", id_usuario_creacion) :
                new ObjectParameter("id_usuario_creacion", typeof(string));
    
            var nombres_ingresadosParameter = nombres_ingresados != null ?
                new ObjectParameter("nombres_ingresados", nombres_ingresados) :
                new ObjectParameter("nombres_ingresados", typeof(string));
    
            var apellidos_ingresadosParameter = apellidos_ingresados != null ?
                new ObjectParameter("apellidos_ingresados", apellidos_ingresados) :
                new ObjectParameter("apellidos_ingresados", typeof(string));
    
            var fecha_nacimiento_ingresadoParameter = fecha_nacimiento_ingresado != null ?
                new ObjectParameter("fecha_nacimiento_ingresado", fecha_nacimiento_ingresado) :
                new ObjectParameter("fecha_nacimiento_ingresado", typeof(string));
    
            var direccion_ingresadoParameter = direccion_ingresado != null ?
                new ObjectParameter("direccion_ingresado", direccion_ingresado) :
                new ObjectParameter("direccion_ingresado", typeof(string));
    
            var numero_celular_ingresadoParameter = numero_celular_ingresado != null ?
                new ObjectParameter("numero_celular_ingresado", numero_celular_ingresado) :
                new ObjectParameter("numero_celular_ingresado", typeof(string));
    
            var correo_ingresadoParameter = correo_ingresado != null ?
                new ObjectParameter("correo_ingresado", correo_ingresado) :
                new ObjectParameter("correo_ingresado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("registro_persona", tipo_documento_ingresadoParameter, documento_ingresadoParameter, contrasena_ingresadaParameter, rol_ingresadoParameter, cargo_ingresadoParameter, id_usuario_creacionParameter, nombres_ingresadosParameter, apellidos_ingresadosParameter, fecha_nacimiento_ingresadoParameter, direccion_ingresadoParameter, numero_celular_ingresadoParameter, correo_ingresadoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_RepHistAdqPuntos_Result> sp_RepHistAdqPuntos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RepHistAdqPuntos_Result>("sp_RepHistAdqPuntos");
        }
    
        public virtual ObjectResult<sp_RepHistRedmPuntos_Result> sp_RepHistRedmPuntos(string fecha_I, string fecha_F, string servicios)
        {
            var fecha_IParameter = fecha_I != null ?
                new ObjectParameter("Fecha_I", fecha_I) :
                new ObjectParameter("Fecha_I", typeof(string));
    
            var fecha_FParameter = fecha_F != null ?
                new ObjectParameter("Fecha_F", fecha_F) :
                new ObjectParameter("Fecha_F", typeof(string));
    
            var serviciosParameter = servicios != null ?
                new ObjectParameter("Servicios", servicios) :
                new ObjectParameter("Servicios", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RepHistRedmPuntos_Result>("sp_RepHistRedmPuntos", fecha_IParameter, fecha_FParameter, serviciosParameter);
        }
    
        public virtual ObjectResult<sp_RepUsuarios_Result> sp_RepUsuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RepUsuarios_Result>("sp_RepUsuarios");
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> spCreaUsuario(string tipo_documento_ingresado, string documento_ingresado, string contrasena_ingresada, string rol_ingresado, string cargo_ingresado, string id_usuario_creacion, string nombres_ingresados, string apellidos_ingresados, string fecha_nacimiento_ingresado, string direccion_ingresado, string numero_celular_ingresado, string correo_ingresado)
        {
            var tipo_documento_ingresadoParameter = tipo_documento_ingresado != null ?
                new ObjectParameter("tipo_documento_ingresado", tipo_documento_ingresado) :
                new ObjectParameter("tipo_documento_ingresado", typeof(string));
    
            var documento_ingresadoParameter = documento_ingresado != null ?
                new ObjectParameter("documento_ingresado", documento_ingresado) :
                new ObjectParameter("documento_ingresado", typeof(string));
    
            var contrasena_ingresadaParameter = contrasena_ingresada != null ?
                new ObjectParameter("contrasena_ingresada", contrasena_ingresada) :
                new ObjectParameter("contrasena_ingresada", typeof(string));
    
            var rol_ingresadoParameter = rol_ingresado != null ?
                new ObjectParameter("rol_ingresado", rol_ingresado) :
                new ObjectParameter("rol_ingresado", typeof(string));
    
            var cargo_ingresadoParameter = cargo_ingresado != null ?
                new ObjectParameter("cargo_ingresado", cargo_ingresado) :
                new ObjectParameter("cargo_ingresado", typeof(string));
    
            var id_usuario_creacionParameter = id_usuario_creacion != null ?
                new ObjectParameter("id_usuario_creacion", id_usuario_creacion) :
                new ObjectParameter("id_usuario_creacion", typeof(string));
    
            var nombres_ingresadosParameter = nombres_ingresados != null ?
                new ObjectParameter("nombres_ingresados", nombres_ingresados) :
                new ObjectParameter("nombres_ingresados", typeof(string));
    
            var apellidos_ingresadosParameter = apellidos_ingresados != null ?
                new ObjectParameter("apellidos_ingresados", apellidos_ingresados) :
                new ObjectParameter("apellidos_ingresados", typeof(string));
    
            var fecha_nacimiento_ingresadoParameter = fecha_nacimiento_ingresado != null ?
                new ObjectParameter("fecha_nacimiento_ingresado", fecha_nacimiento_ingresado) :
                new ObjectParameter("fecha_nacimiento_ingresado", typeof(string));
    
            var direccion_ingresadoParameter = direccion_ingresado != null ?
                new ObjectParameter("direccion_ingresado", direccion_ingresado) :
                new ObjectParameter("direccion_ingresado", typeof(string));
    
            var numero_celular_ingresadoParameter = numero_celular_ingresado != null ?
                new ObjectParameter("numero_celular_ingresado", numero_celular_ingresado) :
                new ObjectParameter("numero_celular_ingresado", typeof(string));
    
            var correo_ingresadoParameter = correo_ingresado != null ?
                new ObjectParameter("correo_ingresado", correo_ingresado) :
                new ObjectParameter("correo_ingresado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spCreaUsuario", tipo_documento_ingresadoParameter, documento_ingresadoParameter, contrasena_ingresadaParameter, rol_ingresadoParameter, cargo_ingresadoParameter, id_usuario_creacionParameter, nombres_ingresadosParameter, apellidos_ingresadosParameter, fecha_nacimiento_ingresadoParameter, direccion_ingresadoParameter, numero_celular_ingresadoParameter, correo_ingresadoParameter);
        }
    
        public virtual ObjectResult<string> spInsertVehiculo(string usuario, string placa, string marca, string referencia, string cilindraje)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var placaParameter = placa != null ?
                new ObjectParameter("placa", placa) :
                new ObjectParameter("placa", typeof(string));
    
            var marcaParameter = marca != null ?
                new ObjectParameter("marca", marca) :
                new ObjectParameter("marca", typeof(string));
    
            var referenciaParameter = referencia != null ?
                new ObjectParameter("referencia", referencia) :
                new ObjectParameter("referencia", typeof(string));
    
            var cilindrajeParameter = cilindraje != null ?
                new ObjectParameter("cilindraje", cilindraje) :
                new ObjectParameter("cilindraje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spInsertVehiculo", usuarioParameter, placaParameter, marcaParameter, referenciaParameter, cilindrajeParameter);
        }
    
        public virtual ObjectResult<UsuariosVehiculo_Result> UsuariosVehiculo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UsuariosVehiculo_Result>("UsuariosVehiculo");
        }
    }
}
