//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        public string id_reserva { get; set; }
        public Nullable<int> id_estacion { get; set; }
        public string id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_reserva { get; set; }
        public Nullable<int> puntos_redimidos { get; set; }
    
        public virtual estaciones_de_servicio estaciones_de_servicio { get; set; }
        public virtual personas personas { get; set; }
    }
}
