//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reservas()
        {
            this.detalle_reserva = new HashSet<detalle_reserva>();
        }
    
        public int id_reserva { get; set; }
        public Nullable<int> id_estacion { get; set; }
        public string id_usuario { get; set; }
        public string fecha_reserva { get; set; }
        public Nullable<int> puntos_redimidos { get; set; }
        public Nullable<int> hora_reserva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalle_reserva> detalle_reserva { get; set; }
        public virtual estaciones_de_servicio estaciones_de_servicio { get; set; }
        public virtual personas personas { get; set; }
    }
}
