//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public string documento_usuario { get; set; }
        public string placa_vehiculo_cliente { get; set; }
        public string codigo_vehiculo { get; set; }
        public string marca_vehiculo { get; set; }
        public string referencia_vehiculo { get; set; }
        public string cilindraje_vehiculo { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual detalle_vehiculos detalle_vehiculos { get; set; }
        public virtual personas personas { get; set; }
    }
}
